### ISSUE TITLE
Failed pods on quickstart setup

### ISSUE THREAD

**Issue by mohsinansarirepo** [egovernments/DIGIT-DevOps#1647]
Few months back quickstart setup was done, it was running fine with no issues but now quickstart setup on different machine is giving issues with 5 failed pods namely egov-user, egov-enc-service, egov-indexer, egov-persister and egov-persister. Below are some logs

I0514 07:34:36.340479       1 main.go:270] starting up: ["/git-sync"]
E0514 07:34:37.176641       1 main.go:294] error syncing repo: error running command: exit status 128: "Cloning into '/work-dir'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"

**Comment by Gowtham-egov** [comment]
Hi Mohsin. The above issue, what you have shared is due to known-host was not updated in your secret.yaml file. Follow this link and change the known-host value with the highlighted one under secrets/git-creds in your cluster.
https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/#:~:text=github.com%20ssh,S5hpQs%2Bp1vN1/wsjk%3D

**Comment by mohsinansarirepo** [comment]
Thank you for the guidance. All pods are in running state now. 
We were using "Quickstart" branch and changed the key as you suggested.
We are starting our work on Finance module of digit and will be highly obliged if we get your guidance.

**Comment by Gowtham-egov** [comment]
Sure

**Comment by mohsinansarirepo** [comment]
Hi @Gowtham-egov ,
We have tried "Quickstart" on local machine to get familiar with the installation steps. Now, we are trying to install finance module by cloning the "master" repository and following the similar steps as followed in quickstart but after installation pods are not created.

Please guide us what we are missing or there is some other installation method which we have to follow.
